name: Deploy Staging 

on: 
    push: 
        branches: 
            - staging cd
            
permissions: 
    contents: read 
    packages: read 
    
jobs: 
    deploy: 
        uses: ./.github/workflows/deploy.yml 
        with: 
            environment: staging 
            image_tag: sha-${{ github.sha }} 
            
        secrets: 
            HOST: ${{ secrets.STAGING_HOST }} 
            USER: ${{ secrets.STAGING_USER }} 
            SSH_KEY: ${{ secrets.STAGING_SSH_KEY }} 
            GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }} 
            GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }} 
            
            
    notify: 
        needs: deploy 
        if: always() 
        
        uses: ./.github/workflows/notifications.yml 
        with: 
            status: ${{ needs.deploy.result }} 
            environment: Staging 
            title: Staging Deployment 
            message: Staging deployment completed. 
            
        secrets: inherit